# action.yaml
name: 'Promtool Github Action'
author: 'karancode <karanthanvi0@gmail.com>'
description: 'Github action for promtool - quickly check whether a rule file is syntactically correct'
branding:
  icon: 'sun'
  color: 'orange'
inputs:
  prom_version:
    description: 'Prometheus version'
    required: false
    default: '2.16.0'
  prom_check_subcommand:
    description: 'Promtool check command - config|rules'
    required: true
  prom_check_files:
    description: 'Promtheus config/rules file to check'
    required: true
  prom_comment:
    description: 'Comment promtool output'
    required: false
    default: '0'
outputs:
  promtool_output:
    description: 'Output of promtool check'
runs:
  using: 'docker'
  image: 'Dockerfile'
